
#Broken Blocks Data
[brokenBlocks]
	#Default broken blocks data
	default = []

#Around Blocks Table Data
[aroundBlocksTable]
	#Default around blocks table data
	default = []

#Perimeter Blocks Table Data
[perimeterBlocksTable]
	#Default perimeter blocks table data
	default = []

#Main Block Position
[mainBlockPos]
	#Default main block position
	default = "0,0,0"

